name: Java CI

on:
  push:
    branches: ["main","master"]
  pull_request:
    branches: ["main","master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 #Pega o histórico de todos os commits

    - name: Configurar Java JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Cache do SonarCloud
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Executar testes JUnit e Análise SonarCloud com Maven
      #Faz o mesmo que o mvn test, porém
      # 
      # - Após os testes, gera um relatorio de 
      #   cobertura do código utilizado nos 
      #   testes com JaCoCo
      #
      # - Aciona o plugin do SonarCloud e envia 
      #   o código e o resultado dos testes para 
      #   o Sonar

      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #É injetado, não precisa declarar
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run : mvn -B -X verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar